name: Docker Image CI

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  pull_request:

env:
  SERVICE_NAME: 'gg-user-management'

jobs:
  build:
    name: Gradle build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ACTION_READ_ALL_PACKAGES }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build, check, test, code coverage
        run: ./gradlew build
